### ISSUE TITLE
Problems with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [zmeers/readabs#1]
I'm in the process of preparing the release for _tibble_ 2.0.0. The _readabs_ package imports or suggests _tibble_.

I'm seeing errors when testing your package with the dev version of _tibble_. The errors seem to come from assumptions about the names of renamed columns which have changed in _tibble_ 2.0.0.

Could you please install the development version of _tibble_ and run the tests in your package, so that we get a better understanding of the problem?

See https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/ for details on the upcoming release.

**Comment by MattCowgill** [comment]
I think this could be fixed by replacing line 27 in read_abs_data() with:

`colnames(dat)[1] <- "Date"`
